### ISSUE TITLE
Build fails for the following reasons

### ISSUE THREAD

**Issue by esabunor** [scalessec/Toast-Swift#115] opened 2018-09-19 06:58 UTC
Build fails for the following reasons:
L355 RunLoop.main.add(timer, forMode: .common) instead of RunLoop.main.add(timer, forMode: .commonModes)
and 
L326 let activityIndicatorView = UIActivityIndicatorView(style: .whiteLarge) instead of let activityIndicatorView = UIActivityIndicatorView(activityIndicatorStyle: .whiteLarge)

Thank you the beautiful project btw.

**Comment by scalessec** [comment] 2018-09-20 00:10
Please check closed issues before opening a new one. This is a duplicate of #114. `4.0.0` requires Swift 4.2 and Xcode 10.

**Closed by scalessec** 2018-09-20 00:10 UTC
